Exposing the data definition epsilon variable
Sequal32/simconnect-rust pull request #10
Opened 2023-12-21 15:58 UTC by BitsAndDroids

When the epsilon of all variables in a data definition is set to 0.0, the sim will return an abundance of data when data is flagged as on change.
For example, every mm change of altitude is seen as a change in the variable, while in reality, you most likely only need changes per foot. Exposing the epsilon as a function parameter enables cleaner outputs.
This also simplifies our ability to use the data changed flag to send data to microprocessors (without flooding them with unused data).

`conn.add_data_definition(0, "PLANE LATITUDE", "Degrees", simconnect::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX, 0.0); // this will trigger an update every minor change < 1.0 degree
conn.add_data_definition(0, "PLANE LONGITUDE", "Degrees", simconnect::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX, 1.0); // this will only trigger an update every 1.0 degree change`

2023-12-24 10:55 UTC, BitsAndDroids commented
Added an extra example to explain how to utilize the epsilon variable and put both examples in the example folder

2023-12-26 08:49 UTC, Sequal32 requested changes
Thanks so much for your contribution and including examples with detailed descriptions! These will make it much easier for developers to start using the crate and know how to read floats/strings. 

Apologies for not including the epsilon value in the function call. I commented on a few typos and a suggestion to combine some lines.

2023-12-26 08:49 UTC, Sequal32 commented on Readme.md
> +            let sim_data_ptr = sim_data as *const DataStruct;
We can save some lines by making these one line

```suggestion
            let sim_data_ptr =  std::ptr::addr_of!(data.dwData) as *const DataStruct;
```

2023-12-26 08:49 UTC, Sequal32 commented on examples/aircraft_updates_on_change/main.rs
> +// To allign the memory we have to set a fixed max size to the returned variables from the game
Typo

```suggestion
// To align the memory we have to set a fixed max size to the returned variables from the game
```

2023-12-26 08:49 UTC, Sequal32 commented on examples/aircraft_updates_on_change/main.rs
> +    // (including integers, the memory allignment will handle the)
```suggestion
    // (including integers, which the memory alignment will handle)
```

2023-12-26 08:49 UTC, Sequal32 commented on examples/aircraft_updates_on_change/main.rs
> +                        //Here we match the define_id we've passed using the request_data_on_sim_object
```suggestion
                        // Here we match the define_id we've passed using the request_data_on_sim_object
```

2023-12-26 08:49 UTC, Sequal32 commented on examples/aircraft_updates_on_change/main.rs
> +                            // itterate through the array of data structs
```suggestion
                            // Iterate through the array of data structs
```

2023-12-26 08:49 UTC, Sequal32 commented on examples/aircraft_updates_on_change/main.rs
> +                            // To allign the memory we have allocated an array of 255 elements to the datastruct
```suggestion
                            // To align the memory we have allocated an array of 255 elements to the datastruct
```

2023-12-26 08:49 UTC, Sequal32 commented on examples/aircraft_updates_on_change/main.rs
> +                            // To only itterate over valid elements in the array
```suggestion
                            // To only iterate over valid elements in the array
```

2023-12-26 11:00 UTC, BitsAndDroids commented
@Sequal32 Whoops, I just started using RustRover and haven't configured my spellchecker yet. I've amended the spelling errors (and found some more).

2023-12-27 06:09 UTC, Sequal32 commented
Awesome, the comments look great. I ran `cargo clippy` over the whole project and fixed those warnings (and added print statements for the `Open` and `Quit` events as well). Thanks so much for your contribution and happy holidays!

2023-12-27 06:09 UTC, Sequal32 approved these changes

2023-12-27 06:11 UTC, merged

2024-03-19 20:00 UTC, MrMinimal commented
I updated to the latest version and saw all these changes. Superb contribution, the examples will be amazing for new devs getting into this. Thank you!