Fixed build when used in Github Actions
Sequal32/simconnect-rust pull request #20
Opened 2024-06-22 09:33 UTC by BitsAndDroids

2024-07-05 08:51 UTC, BitsAndDroids commented
@Sequal32 If you want help to maintain this repo, I'm down to help you out. If interested, you can reach me at dave@{myusername}.com (to avoid bots scraping the address).

2024-07-10 03:10 UTC, Sequal32 requested changes
Hey @BitsAndDroids thanks so much for your contribution again, and sorry for the delay! I'm going to be active enough to maintain this repo again, and feel free to keep submitting PRs. I'll hopefully be able to get to them quicker.

2024-07-10 03:10 UTC, Sequal32 commented on build.rs
> +        .allowlist_type("HANDLE")
What's the reason for adding this?

2024-07-10 03:10 UTC, Sequal32 commented on libsrc/include/SimConnect.hpp
> +#include <windows.h>
Please remove all formatting changes and make this lowercase change the only diff in the file.

Also for the record, [this stack overflow answer](https://stackoverflow.com/a/15466951) also provides reasoning and supports the change.

2024-07-10 07:05 UTC, BitsAndDroids commented
> Hey @BitsAndDroids thanks so much for your contribution again, and sorry for the delay! I'm going to be active enough to maintain this repo again, and feel free to keep submitting PRs. I'll hopefully be able to get to them quicker.

I'm just glad to see that you're doing well. I also implemented the changes and changed the version (0.4.0 wasn't semver).

2024-07-10 14:33 UTC, Sequal32 approved these changes

2024-07-10 14:33 UTC, merged