Move sample code to example directory
Sequal32/simconnect-rust pull request #9
Opened 2023-12-06 08:05 UTC by MrMinimal

For convenience I have moved the sample code to an actual example.
It can be run using a built-in `cargo` command, which I have added to the README.

These lines of the example don't compile with the latest simconnect version anymore and are therefore commented out:
https://github.com/MrMinimal/simconnect-rust/blob/ebef846aa453c5daa6821742fa56084818ad5c6f/examples/connection/main.rs#L54

Edits welcome 😊

2023-12-24 10:56 UTC, BitsAndDroids commented
I've opened a pr as well that required an extra example. I've incorporated your suggestion but also fixed the broken example. 
(if this repo is still maintained that is)
https://github.com/Sequal32/simconnect-rust/pull/10

2023-12-26 08:26 UTC, MrMinimal commented
@BitsAndDroids Thank you so much, I had a look at your PR and it should greatly improve the usability of this library.

Though I doubt that this repo is still active. The alternatives like https://github.com/mihai-dinculescu/simconnect-sdk-rs seem fun but are not feature conplete. Fork? 🤠

2023-12-26 08:34 UTC, Sequal32 requested changes
Sorry just got around to looking at this now, and thanks so much for the contribution! These changes will make the Repo easier to demo with the example binary now. 

Just a couple of changes.

2023-12-26 08:34 UTC, Sequal32 commented on examples/connection/main.rs
> +                        // let sim_data: DataStruct = transmute_copy(&data.dwData);
I don't think these should be commented out

2023-12-26 08:34 UTC, Sequal32 commented on Readme.md
> +*This crate is in its early stages and API breaking changes can be pushed at any moment. It's recommended to use the exact version "0.X.X"*
This was removed in 6da1fc65d9aca4f753fcce7004f6232a919e7452
```suggestion

```

2023-12-26 08:35 UTC, Sequal32 commented
Sorry just got around to looking at this now, and thanks for your contribution! I'll close this in favor of @BitsAndDroids 's PR #10.

2023-12-26 08:35 UTC, closed without merging

2023-12-26 08:50 UTC, MrMinimal commented
@Sequal32 Cheers and happy holidays, really appreciate your project!